# This file was generated by GoReleaser. DO NOT EDIT.
cask "bak" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "92e037fb77340141e1ebd97537a761b75314215d0ccabfdea8be9bd9b65472be"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fbc88b62eabb85e4ffedec2376ee41fde891d2a3c6812dcb4b0ab5b3ae82913"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "36419eb88e3e597b49982625c7a7e322dfdba370d422fff0bd1e9b2cd8d10274"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18fbab1866e93139f3136dea3c4f5d8fc7b74ec2ffa04d39556c980b6247683f"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bak"
  desc "Backup and restore your AI coding setup across machines"
  homepage "https://github.com/danielxxomg/bak-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bak"]
    end
  end

  # No zap stanza required

end
