# This file was generated by GoReleaser. DO NOT EDIT.
cask "bak" do
  version "1.5.0-rc1"

  on_macos do
    on_arm do
      sha256 "336cec97840fa730fb2c41c1cdac75eb926639674413f6889d84fda95ab563dd"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7785ce84f92596f1de2993ca27ac141ab885d06a19a0ff5eed2ce866faaecd59"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5507c3dbaf831779db77c2d56aeba19398b3225a8714c2971c59c7afa4b0769e"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4607b07ab58e23db80f05526bcc0dc7432dc9686af4e45c8dc3f4d8c0bf37049"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bak"
  desc "Backup and restore your AI coding setup across machines"
  homepage "https://github.com/danielxxomg/bak-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bak"]
    end
  end

  # No zap stanza required
end
