# This file was generated by GoReleaser. DO NOT EDIT.
cask "bak" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "4bea8a57d026d828ed792a46106affcb1530b84339cf9078ccd0222fcd5f8164"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54b5a447e21d41d3bd9a21dacdba4176f526b28f96e440a074b836bcc9e05a45"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "598a6e47d609422891c95f89a101d38e571ac44a55cb7a0615fdabf92829776a"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "02a631dddbd9100705b6e89c3749e71466bdfd381991f3ca4120b16771e724d5"
      url "https://github.com/danielxxomg/bak-cli/releases/download/v#{version}/bak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "bak"
  desc "Backup and restore your AI coding setup across machines"
  homepage "https://github.com/danielxxomg/bak-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bak"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bak"]
    end
  end

  # No zap stanza required

end
